### ISSUE TITLE
1.6.1版本的音乐播放功能有问题

### ISSUE THREAD

**Issue by GH6324** [xiaopanglian/icefox#4]
1.5.0版本升级到1.6.1版本插入音乐之后报错，点击播放按钮不能正常播放音乐，不知道是我的问题还是

F12控制台报错如下图

![image](https://github.com/xiaopanglian/icefox/assets/47879885/ed875312-156c-4393-b9c3-a9c1e09f645e)

**Comment by xiaopanglian** [comment]
发下你地址看下呢？或者加群527838299 沟通下，我这边验证是没复现这个BUG的
